name: Flake8
on: [push]
jobs:
  linter:
    name: Линтер
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.0
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install flake8==6.0.0 flake8-bandit==4.1.1 bandit==1.7.4
    - name: Flake8
      run: flake8 .
